import { Category, CategoryItem, CreditCard, HouseMember, RecurringBill, SavingsGoal, Transaction } from './types';

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'moradia',
    label: 'Aluguel & Condomínio',
    icon: 'Home',
    color: 'text-indigo-600',
    bg: 'bg-indigo-50 border-indigo-200 text-indigo-700',
    type: 'expense',
  },
  {
    id: 'supermercado',
    label: 'Supermercado & Feira',
    icon: 'ShoppingCart',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 border-emerald-200 text-emerald-700',
    type: 'expense',
  },
  {
    id: 'contas',
    label: 'Contas (Água, Luz, Net, Gás)',
    icon: 'Zap',
    color: 'text-amber-600',
    bg: 'bg-amber-50 border-amber-200 text-amber-700',
    type: 'expense',
  },
  {
    id: 'manutencao',
    label: 'Manutenção & Limpeza',
    icon: 'Wrench',
    color: 'text-slate-600',
    bg: 'bg-slate-100 border-slate-300 text-slate-700',
    type: 'expense',
  },
  {
    id: 'alimentacao_fora',
    label: 'Delivery & Restaurantes',
    icon: 'Utensils',
    color: 'text-orange-600',
    bg: 'bg-orange-50 border-orange-200 text-orange-700',
    type: 'expense',
  },
  {
    id: 'transporte',
    label: 'Transporte & Carro',
    icon: 'Car',
    color: 'text-blue-600',
    bg: 'bg-blue-50 border-blue-200 text-blue-700',
    type: 'expense',
  },
  {
    id: 'saude',
    label: 'Saúde & Farmácia',
    icon: 'HeartPulse',
    color: 'text-rose-600',
    bg: 'bg-rose-50 border-rose-200 text-rose-700',
    type: 'expense',
  },
  {
    id: 'educacao',
    label: 'Educação & Cursos',
    icon: 'GraduationCap',
    color: 'text-purple-600',
    bg: 'bg-purple-50 border-purple-200 text-purple-700',
    type: 'expense',
  },
  {
    id: 'pets',
    label: 'Pets (Ração & Vet)',
    icon: 'PawPrint',
    color: 'text-teal-600',
    bg: 'bg-teal-50 border-teal-200 text-teal-700',
    type: 'expense',
  },
  {
    id: 'lazer',
    label: 'Lazer & Família',
    icon: 'Tv',
    color: 'text-pink-600',
    bg: 'bg-pink-50 border-pink-200 text-pink-700',
    type: 'expense',
  },
  {
    id: 'investimento',
    label: 'Reserva & Economia',
    icon: 'PiggyBank',
    color: 'text-cyan-600',
    bg: 'bg-cyan-50 border-cyan-200 text-cyan-700',
    type: 'expense',
  },
  {
    id: 'outros',
    label: 'Outras Despesas',
    icon: 'Package',
    color: 'text-zinc-600',
    bg: 'bg-zinc-100 border-zinc-200 text-zinc-700',
    type: 'both',
  },
];

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card-1',
    name: 'Nubank Ultravioleta',
    bank: 'Nubank',
    lastDigits: '7412',
    limit: 12000,
    closingDay: 18,
    dueDay: 25,
    holderId: 'm1',
    color: 'purple',
    brand: 'mastercard',
  },
  {
    id: 'card-2',
    name: 'Inter Black',
    bank: 'Banco Inter',
    lastDigits: '3098',
    limit: 8500,
    closingDay: 8,
    dueDay: 15,
    holderId: 'm2',
    color: 'orange',
    brand: 'mastercard',
  },
  {
    id: 'card-3',
    name: 'Itaú Platinum',
    bank: 'Itaú',
    lastDigits: '5521',
    limit: 6000,
    closingDay: 22,
    dueDay: 29,
    holderId: 'm3',
    color: 'blue',
    brand: 'visa',
  },
];

export const CATEGORY_DETAILS: Record<string, { label: string; icon: string; color: string; bg: string }> = {
  moradia: {
    label: 'Aluguel & Condomínio',
    icon: 'Home',
    color: 'text-indigo-600',
    bg: 'bg-indigo-50 border-indigo-200 text-indigo-700',
  },
  supermercado: {
    label: 'Supermercado & Feira',
    icon: 'ShoppingCart',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 border-emerald-200 text-emerald-700',
  },
  contas: {
    label: 'Contas (Água, Luz, Gás, Net)',
    icon: 'Zap',
    color: 'text-amber-600',
    bg: 'bg-amber-50 border-amber-200 text-amber-700',
  },
  manutencao: {
    label: 'Manutenção & Limpeza',
    icon: 'Wrench',
    color: 'text-slate-600',
    bg: 'bg-slate-100 border-slate-300 text-slate-700',
  },
  alimentacao_fora: {
    label: 'Delivery & Restaurantes',
    icon: 'Utensils',
    color: 'text-orange-600',
    bg: 'bg-orange-50 border-orange-200 text-orange-700',
  },
  transporte: {
    label: 'Transporte & Carro',
    icon: 'Car',
    color: 'text-blue-600',
    bg: 'bg-blue-50 border-blue-200 text-blue-700',
  },
  saude: {
    label: 'Saúde & Farmácia',
    icon: 'HeartPulse',
    color: 'text-rose-600',
    bg: 'bg-rose-50 border-rose-200 text-rose-700',
  },
  educacao: {
    label: 'Educação & Cursos',
    icon: 'GraduationCap',
    color: 'text-purple-600',
    bg: 'bg-purple-50 border-purple-200 text-purple-700',
  },
  pets: {
    label: 'Pets (Ração & Vet)',
    icon: 'PawPrint',
    color: 'text-teal-600',
    bg: 'bg-teal-50 border-teal-200 text-teal-700',
  },
  lazer: {
    label: 'Lazer & Família',
    icon: 'Tv',
    color: 'text-pink-600',
    bg: 'bg-pink-50 border-pink-200 text-pink-700',
  },
  investimento: {
    label: 'Reserva & Economia',
    icon: 'PiggyBank',
    color: 'text-cyan-600',
    bg: 'bg-cyan-50 border-cyan-200 text-cyan-700',
  },
  outros: {
    label: 'Outras Despesas',
    icon: 'Package',
    color: 'text-zinc-600',
    bg: 'bg-zinc-100 border-zinc-200 text-zinc-700',
  },
};

export const INITIAL_MEMBERS: HouseMember[] = [
  {
    id: 'm1',
    name: 'Carlos Oliveira',
    avatarColor: 'bg-blue-600',
    role: 'Organizador da Casa',
    email: 'carlos@casa.com',
    monthlyIncome: 6500,
  },
  {
    id: 'm2',
    name: 'Mariana Santos',
    avatarColor: 'bg-emerald-600',
    role: 'Moradora',
    email: 'mariana@casa.com',
    monthlyIncome: 5800,
  },
  {
    id: 'm3',
    name: 'Lucas Ferreira',
    avatarColor: 'bg-amber-600',
    role: 'Morador',
    email: 'lucas@casa.com',
    monthlyIncome: 4200,
  },
];

// Comprovantes em SVG Data URL para demonstração realista imediata
export const SAMPLE_RECEIPTS = {
  supermercado: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="550" viewBox="0 0 400 550" fill="none"><rect width="400" height="550" fill="%23FFFFFF" rx="12"/><rect x="20" y="20" width="360" height="510" fill="%23F8FAFC" stroke="%23CBD5E1" stroke-width="2" stroke-dasharray="6 6" rx="8"/><text x="200" y="60" font-family="monospace" font-size="20" font-weight="bold" fill="%231E293B" text-anchor="middle">SUPERMERCADO CENTRAL</text><text x="200" y="85" font-family="monospace" font-size="12" fill="%2364748B" text-anchor="middle">CNPJ: 12.345.678/0001-90</text><line x1="40" y1="105" x2="360" y2="105" stroke="%23CBD5E1" stroke-width="1"/><text x="50" y="140" font-family="monospace" font-size="13" fill="%23334155">Arroz 5kg Tipo 1</text><text x="350" y="140" font-family="monospace" font-size="13" fill="%23334155" text-anchor="end">R$ 29,90</text><text x="50" y="170" font-family="monospace" font-size="13" fill="%23334155">Feijao Preto 1kg x2</text><text x="350" y="170" font-family="monospace" font-size="13" fill="%23334155" text-anchor="end">R$ 17,80</text><text x="50" y="200" font-family="monospace" font-size="13" fill="%23334155">Carnes Bovinas (Alcatra)</text><text x="350" y="200" font-family="monospace" font-size="13" fill="%23334155" text-anchor="end">R$ 88,50</text><text x="50" y="230" font-family="monospace" font-size="13" fill="%23334155">Frutas, Legumes &amp; Verduras</text><text x="350" y="230" font-family="monospace" font-size="13" fill="%23334155" text-anchor="end">R$ 64,30</text><text x="50" y="260" font-family="monospace" font-size="13" fill="%23334155">Produtos de Limpeza Casa</text><text x="350" y="260" font-family="monospace" font-size="13" fill="%23334155" text-anchor="end">R$ 79,20</text><line x1="40" y1="300" x2="360" y2="300" stroke="%23CBD5E1" stroke-width="2"/><text x="50" y="340" font-family="monospace" font-size="18" font-weight="bold" fill="%230F172A">TOTAL COMPRA:</text><text x="350" y="340" font-family="monospace" font-size="18" font-weight="bold" fill="%23059669" text-anchor="end">R$ 279,70</text><rect x="50" y="375" width="300" height="40" fill="%23ECFDF5" rx="6"/><text x="200" y="400" font-family="sans-serif" font-size="12" font-weight="bold" fill="%23065F46" text-anchor="middle">✓ PAGAMENTO APROVADO VIA CARTAO</text><text x="200" y="460" font-family="monospace" font-size="11" fill="%2394A3B8" text-anchor="middle">Autenticacao: 8F39-44A1-E72C-991A</text><text x="200" y="485" font-family="monospace" font-size="11" fill="%2394A3B8" text-anchor="middle">Obrigado pela preferencia!</text></svg>`,
  pixLuz: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="550" viewBox="0 0 400 550" fill="none"><rect width="400" height="550" fill="%23FFFFFF" rx="12"/><rect x="20" y="20" width="360" height="510" fill="%23F0FDF4" stroke="%2386EFAC" stroke-width="2" rx="8"/><circle cx="200" cy="80" r="32" fill="%2322C55E"/><path d="M188 80l8 8 16-16" stroke="white" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><text x="200" y="140" font-family="sans-serif" font-size="18" font-weight="bold" fill="%2314532D" text-anchor="middle">Comprovante de Pagamento Pix</text><text x="200" y="165" font-family="sans-serif" font-size="13" fill="%23166534" text-anchor="middle">Transacao realizada com sucesso</text><rect x="40" y="195" width="320" height="85" fill="%23FFFFFF" rx="8" stroke="%23BBF7D0"/><text x="60" y="225" font-family="sans-serif" font-size="12" fill="%2364748B">Valor Pago</text><text x="60" y="258" font-family="sans-serif" font-size="24" font-weight="bold" fill="%230F172A">R$ 215,40</text><line x1="40" y1="305" x2="360" y2="305" stroke="%23BBF7D0" stroke-width="1"/><text x="50" y="335" font-family="sans-serif" font-size="12" fill="%2364748B">Beneficiario:</text><text x="50" y="355" font-family="sans-serif" font-size="14" font-weight="bold" fill="%231E293B">ENEL DISTRIBUICAO S.A.</text><text x="50" y="390" font-family="sans-serif" font-size="12" fill="%2364748B">Conta Contrato / Referencia:</text><text x="50" y="410" font-family="sans-serif" font-size="13" fill="%231E293B">Energia Eletrica Residencial - Mes Atual</text><text x="50" y="445" font-family="sans-serif" font-size="12" fill="%2364748B">ID da Transacao:</text><text x="50" y="465" font-family="monospace" font-size="11" fill="%23334155">E0003816620261005143000</text></svg>`,
  internet: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="550" viewBox="0 0 400 550" fill="none"><rect width="400" height="550" fill="%23FFFFFF" rx="12"/><rect x="20" y="20" width="360" height="510" fill="%23EFF6FF" stroke="%2393C5FD" stroke-width="2" rx="8"/><text x="200" y="70" font-family="sans-serif" font-size="20" font-weight="bold" fill="%231E3A8A" text-anchor="middle">CLARO FIBRA 500 MEGA</text><text x="200" y="95" font-family="sans-serif" font-size="12" fill="%233B82F6" text-anchor="middle">Fatura Mensal de Internet Residencial</text><line x1="40" y1="120" x2="360" y2="120" stroke="%23BFDBFE" stroke-width="1"/><text x="50" y="160" font-family="sans-serif" font-size="13" fill="%23475569">Titular:</text><text x="350" y="160" font-family="sans-serif" font-size="13" font-weight="bold" fill="%230F172A" text-anchor="end">Casa - Moradores</text><text x="50" y="195" font-family="sans-serif" font-size="13" fill="%23475569">Velocidade:</text><text x="350" y="195" font-family="sans-serif" font-size="13" fill="%230F172A" text-anchor="end">500 Mbps Download / 250 Up</text><text x="50" y="230" font-family="sans-serif" font-size="13" fill="%23475569">Periodo de Utilizacao:</text><text x="350" y="230" font-family="sans-serif" font-size="13" fill="%230F172A" text-anchor="end">Mes Corrente</text><line x1="40" y1="260" x2="360" y2="260" stroke="%23BFDBFE" stroke-width="2"/><text x="50" y="300" font-family="sans-serif" font-size="16" font-weight="bold" fill="%231E293B">VALOR TOTAL:</text><text x="350" y="300" font-family="sans-serif" font-size="20" font-weight="bold" fill="%232563EB" text-anchor="end">R$ 149,90</text><rect x="50" y="340" width="300" height="48" fill="%23DBEAFE" rx="8"/><text x="200" y="370" font-family="sans-serif" font-size="13" font-weight="bold" fill="%231E40AF" text-anchor="middle">STATUS: QUITADO VIA DEBITO</text><text x="200" y="440" font-family="monospace" font-size="11" fill="%2364748B" text-anchor="middle">Aut. Bancaria: CLR-2026-9938210</text></svg>`,
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Mês atual (Outubro 2026)
  {
    id: 't-1',
    description: 'Salário Carlos (Aporte Casa)',
    amount: 4500,
    type: 'income',
    category: 'moradia',
    date: '2026-10-01',
    paidById: 'm1',
    splitType: 'individual',
    splitMembers: ['m1'],
    notes: 'Contribuição para o caixa da casa',
    isShared: true,
    createdAt: '2026-10-01T08:00:00Z',
  },
  {
    id: 't-2',
    description: 'Salário Mariana (Aporte Casa)',
    amount: 4200,
    type: 'income',
    category: 'moradia',
    date: '2026-10-01',
    paidById: 'm2',
    splitType: 'individual',
    splitMembers: ['m2'],
    notes: 'Contribuição para o caixa da casa',
    isShared: true,
    createdAt: '2026-10-01T08:10:00Z',
  },
  {
    id: 't-3',
    description: 'Salário Lucas (Aporte Casa)',
    amount: 3000,
    type: 'income',
    category: 'moradia',
    date: '2026-10-01',
    paidById: 'm3',
    splitType: 'individual',
    splitMembers: ['m3'],
    notes: 'Contribuição para o caixa da casa',
    isShared: true,
    createdAt: '2026-10-01T08:20:00Z',
  },
  {
    id: 't-4',
    description: 'Aluguel do Imóvel + IPTU',
    amount: 2850,
    type: 'expense',
    category: 'moradia',
    date: '2026-10-02',
    paidById: 'm1',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    notes: 'Pago via transferência bancária imobiliária',
    isShared: true,
    createdAt: '2026-10-02T10:00:00Z',
  },
  {
    id: 't-5',
    description: 'Condomínio Residencial',
    amount: 680,
    type: 'expense',
    category: 'moradia',
    date: '2026-10-03',
    paidById: 'm2',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    notes: 'Boleto pago no banco',
    isShared: true,
    createdAt: '2026-10-03T11:00:00Z',
  },
  {
    id: 't-6',
    description: 'Compras Semanais Supermercado',
    amount: 620.40,
    type: 'expense',
    category: 'supermercado',
    date: '2026-10-04',
    paidById: 'm2',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    receiptUrl: SAMPLE_RECEIPTS.supermercado,
    receiptName: 'cupom_fiscal_mercado_04_out.png',
    paymentMethod: 'cartao',
    creditCardId: 'card-1',
    notes: 'Compra do mês no cartão Nubank',
    isShared: true,
    createdAt: '2026-10-04T15:30:00Z',
  },
  {
    id: 't-7',
    description: 'Conta de Energia Elétrica (Enel)',
    amount: 215.40,
    type: 'expense',
    category: 'contas',
    date: '2026-10-05',
    paidById: 'm1',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    receiptUrl: SAMPLE_RECEIPTS.pixLuz,
    receiptName: 'comprovante_pix_enel.png',
    paymentMethod: 'pix',
    notes: 'Fatura do mês quitada',
    isShared: true,
    createdAt: '2026-10-05T09:15:00Z',
  },
  {
    id: 't-8',
    description: 'Internet Fibra 500MB',
    amount: 149.90,
    type: 'expense',
    category: 'contas',
    date: '2026-10-05',
    paidById: 'm3',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    receiptUrl: SAMPLE_RECEIPTS.internet,
    receiptName: 'fatura_claro_fibra.png',
    paymentMethod: 'conta',
    notes: 'Débito em conta',
    isShared: true,
    createdAt: '2026-10-05T14:00:00Z',
  },
  {
    id: 't-9',
    description: 'Feira Orgânica & Hortifruti',
    amount: 112.50,
    type: 'expense',
    category: 'supermercado',
    date: '2026-10-06',
    paidById: 'm3',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    paymentMethod: 'pix',
    notes: 'Legumes frescos, frutas e ovos da semana',
    isShared: true,
    createdAt: '2026-10-06T10:45:00Z',
  },
  {
    id: 't-10',
    description: 'Ração e Petiscos (Rex & Mia)',
    amount: 185.00,
    type: 'expense',
    category: 'pets',
    date: '2026-10-06',
    paidById: 'm2',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    paymentMethod: 'cartao',
    creditCardId: 'card-1',
    notes: 'Saco de 15kg ração Golden no cartão Nubank',
    isShared: true,
    createdAt: '2026-10-06T16:20:00Z',
  },
  {
    id: 't-11',
    description: 'Pizza de Domingo da Casa',
    amount: 135.00,
    type: 'expense',
    category: 'alimentacao_fora',
    date: '2026-10-07',
    paidById: 'm1',
    splitType: 'equal',
    splitMembers: ['m1', 'm2', 'm3'],
    paymentMethod: 'cartao',
    creditCardId: 'card-2',
    notes: '2 pizzas grandes no cartão Inter',
    isShared: true,
    createdAt: '2026-10-07T12:00:00Z',
  },
];

export const INITIAL_RECURRING_BILLS: RecurringBill[] = [
  {
    id: 'rb-1',
    name: 'Aluguel do Imóvel',
    amount: 2850,
    category: 'moradia',
    dueDay: 5,
    frequency: 'mensal',
    payerId: 'm1',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 3,
    notes: 'Transferência para conta do proprietário',
    lastPaidMonthYear: '2026-10',
  },
  {
    id: 'rb-2',
    name: 'Condomínio Residencial',
    amount: 680,
    category: 'moradia',
    dueDay: 10,
    frequency: 'mensal',
    payerId: 'm2',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 5,
    notes: 'Boleto bancário da administradora',
    lastPaidMonthYear: '2026-10',
  },
  {
    id: 'rb-3',
    name: 'Energia Elétrica (Enel)',
    amount: 215.40,
    category: 'contas',
    dueDay: 12,
    frequency: 'mensal',
    payerId: 'm1',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 3,
    lastPaidMonthYear: '2026-10',
  },
  {
    id: 'rb-4',
    name: 'Conta de Água (Sabesp)',
    amount: 128.50,
    category: 'contas',
    dueDay: 15,
    frequency: 'mensal',
    payerId: 'm3',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 3,
    notes: 'Vence no meio do mês',
  },
  {
    id: 'rb-5',
    name: 'Internet Fibra 500MB',
    amount: 149.90,
    category: 'contas',
    dueDay: 18,
    frequency: 'mensal',
    payerId: 'm3',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 2,
    lastPaidMonthYear: '2026-10',
  },
  {
    id: 'rb-6',
    name: 'Gás Encanado (Comgás)',
    amount: 85.00,
    category: 'contas',
    dueDay: 22,
    frequency: 'mensal',
    payerId: 'm2',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 4,
  },
  {
    id: 'rb-7',
    name: 'Streaming Casa (Netflix & Spotify)',
    amount: 79.80,
    category: 'lazer',
    dueDay: 25,
    frequency: 'mensal',
    payerId: 'm1',
    splitMembers: ['m1', 'm2', 'm3'],
    reminderDaysBefore: 1,
  },
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'sg-1',
    title: 'Reserva de Emergência da Casa',
    targetAmount: 20000,
    currentAmount: 14500,
    targetDate: '2026-12-31',
    category: 'Segurança',
    icon: 'ShieldCheck',
    color: 'emerald',
    notes: 'Fundo para imprevistos domésticos, vazamentos e manutenções urgentes',
    history: [
      { id: 'gh-1', date: '2026-08-05', amount: 5000, memberId: 'm1', type: 'deposit', note: 'Aporte inicial' },
      { id: 'gh-2', date: '2026-09-05', amount: 4500, memberId: 'm2', type: 'deposit', note: 'Aporte setembro' },
      { id: 'gh-3', date: '2026-10-02', amount: 5000, memberId: 'm1', type: 'deposit', note: 'Aporte outubro' },
    ],
  },
  {
    id: 'sg-2',
    title: 'Reforma da Cozinha & Sala',
    targetAmount: 8000,
    currentAmount: 5200,
    targetDate: '2026-11-20',
    category: 'Conforto',
    icon: 'Hammer',
    color: 'indigo',
    notes: 'Troca da bancada, armários planejados e nova iluminação',
    history: [
      { id: 'gh-4', date: '2026-09-10', amount: 2600, memberId: 'm2', type: 'deposit', note: 'Primeira cota reforma' },
      { id: 'gh-5', date: '2026-10-04', amount: 2600, memberId: 'm3', type: 'deposit', note: 'Segunda cota reforma' },
    ],
  },
  {
    id: 'sg-3',
    title: 'Viagem de Fim de Ano em Família',
    targetAmount: 6000,
    currentAmount: 3900,
    targetDate: '2026-12-15',
    category: 'Lazer',
    icon: 'Plane',
    color: 'amber',
    notes: 'Praia / casa alugada para Réveillon de todos os moradores',
    history: [
      { id: 'gh-6', date: '2026-09-15', amount: 2000, memberId: 'm1', type: 'deposit', note: 'Reserva hospedagem' },
      { id: 'gh-7', date: '2026-10-01', amount: 1900, memberId: 'm2', type: 'deposit', note: 'Passagens / transporte' },
    ],
  },
];
